### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by peter279k** [Th3Mouk/YahooWeatherAPI#1]
Hi @Th3Mouk , thank you for your useful project. When I tried to install the package, I noticed that the Guzzle version is conflicted with my other package. I found that the "goutte" package which you use is used Guzzle ^6.0. But my other package is used Guzzle ^6.2.
How could I do ? Maybe you can only use Guzzle and It doesn't need goutte because the goutte is "Guzzle + Symfony DOM crawler". you should not need the Symfony DOM crawler in this project.
By the way, the Guzzle is now released and the new version is 6.2.1. It fixed the HTTPoxy  vulnerability.
You can checkout this url: https://github.com/guzzle/guzzle/releases.
Maybe I can modify your package and pull request. Thanks.

**Comment by Th3Mouk** [comment]
Hello !

Thanks for your feedback. I'm agree with u, the support of `goutte` can be dropped in favor of guzzle. Many of my others library and projects are still in 6.2.1, i have noticed this vulnerabilty thanks to sensio labs insight notations.

I will have a look, as u can see, this library is quite limited because after the 0.9 release for many website, I no longer use it.

After solving this issue, i will plan the 1.0 milestone.

**Comment by peter279k** [comment]
I think this issue can be closed :) .

**Comment by Th3Mouk** [comment]
Thanks a lot ! Wonderful work
